# Generated by Django 4.2.1 on 2023-05-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('duration', models.DurationField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.deck')),
            ],
        ),
    ]
