# Generated by Django 4.2.1 on 2023-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_deck_date_deck_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
